# Generated by Django 3.2 on 2021-09-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('Description', models.TextField(blank=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Slug', models.SlugField(max_length=48)),
                ('Active', models.BooleanField(default=True)),
                ('In_Stock', models.BooleanField(default=True)),
                ('Date_Updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
